name: Deploy Booking Service

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with: 
          enable-cache: true

      - name: set up python
        run: uv python install 3.12

      - name: install dependencies
        run: uv sync

      - name: run tests
        run: uv run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/projects/booking_service_API
            ls -a
            git pull
            docker compose up -d --build
            docker image prune -f