name: Deploy Booking Service

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis: 
        image: redis:7-alpine
        ports:
          - '6379:6379'
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with: 
          enable-cache: true

      - name: set up python
        run: uv python install 3.12

      - name: install dependencies
        run: uv sync

      - name: run tests
        env:
          DATABASE_URL: 'sqlite+aiosqlite:///:memory:'
          REDIS_URL: 'redis://localhost:6379'
          SECRET_KEY: super_secret_key
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 210
          REFRESH_TOKEN_EXPIRE_DAYS: 70
          DUMMY_HASH: '$argon2id$v=19$m=16,t=2,p=1$T3B1aVBVR0Rla2dkcXg0Nw$fgXeb8zu8jDh7lXGA6nmXQ'
          SUPERUSER_EMAIL: admin@email.com
          SUPERUSER_PASSWORD: adimin_pass
          MAIL_USERNAME: test_username
          MAIL_SERVER: smtp.test.com
          MAIL_PASSWORD: test_password
          MAIL_PORT: 587
        run: uv run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/projects/booking_service_API
            ls -a
            git pull
            docker compose up -d --build
            docker image prune -f